export const TOGGLE_TODO_REQUEST = 'TOGGLE_TODO_REQUEST';
export const TOGGLE_TODO_OPTIMISTIC_SUCCESS = 'TOGGLE_TODO_OPTIMISTIC_SUCCESS';
export const TOGGLE_TODO_FAILURE = 'TOGGLE_TODO_FAILURE';

export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
export const ADD_TODO_OPTIMISTIC_SUCCESS = 'ADD_TODO_OPTIMISTIC_SUCCESS';
export const ADD_TODO_REAL_SUCCESS = 'ADD_TODO_REAL_SUCCESS';
export const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE';

export const ADD_TODOLIST_REQUEST = 'ADD_TODOLIST_REQUEST';
export const ADD_TODOLIST_OPTIMISTIC_SUCCESS = 'ADD_TODOLIST_OPTIMISTIC_SUCCESS';
export const ADD_TODOLIST_REAL_SUCCESS = 'ADD_TODOLIST_REAL_SUCCESS';
export const ADD_TODOLIST_FAILURE = 'ADD_TODOLIST_FAILURE';

export const INIT_APP_REQUEST = 'INIT_APP_REQUEST';
export const INIT_APP_SUCCESS = 'INIT_APP_SUCCESS';
export const INIT_APP_FAILURE = 'INIT_APP_FAILURE';

export const INIT_TODOLISTS_REQUEST = 'INIT_TODOLISTS_REQUEST';
export const INIT_TODOLISTS_SUCCESS = 'INIT_TODOLISTS_SUCCESS';
export const INIT_TODOLISTS_FAILURE = 'INIT_TODOLISTS_FAILURE';

export const INIT_A_TODOLIST = 'INIT_A_TODOLIST';

export const DELETE_TODOLIST_REQUEST = 'DELETE_TODOLIST_REQUEST';
export const DELETE_TODOLIST_OPTIMISTIC_SUCCESS = 'DELETE_TODOLIST_OPTIMISTIC_SUCCESS';
export const DELETE_TODOLIST_FAILURE = 'DELETE_TODOLIST_FAILURE';

export const CHANGE_FILTER_REQUEST = 'CHANGE_FILTER_REQUEST';
export const CHANGE_FILTER_SUCCESS = 'CHANGE_FILTER_SUCCESS';
export const CHANGE_FILTER_FAILURE = 'CHANGE_FILTER_FAILURE';

export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST';
export const DELETE_TODO_OPTIMISTIC_SUCCESS = 'DELETE_TODO_OPTIMISTIC_SUCCESS';
export const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE';

export const SWAP_TODO_REQUEST = 'SWAP_TODO_REQUEST';
export const SWAP_TODO_OPTIMISTIC_SUCCESS = 'SWAP_TODO_OPTIMISTIC_SUCCESS';
export const SWAP_TODO_REAL_SUCCESS = 'SWAP_TODO_REAL_SUCCESS';
export const SWAP_TODO_FAILURE = 'SWAP_TODO_FAILURE';

export const SET_TODOLIST_COLOR_OPTIMISTIC = 'OPTIMISTIC_SET_TODOLIST_COLOR';
export const SET_TODOLIST_COLOR_REAL = 'REAL_SET_TODOLIST_COLOR';

export const INIT_SHORTCUTS_REQUEST = 'INIT_SHORTCUTS_REQUEST';
export const INIT_SHORTCUTS_SUCCESS = 'INIT_SHORTCUTS_SUCCESS';
export const INIT_SHORTCUTS_FAILURE = 'INIT_SHORTCUTS_FAILURE';

export const ADD_SHORTCUT_REQUEST = 'ADD_SHORTCUT_REQUEST';
export const ADD_SHORTCUT_SUCCESS = 'ADD_SHORTCUT_SUCCESS';
export const ADD_SHORTCUT_FAILURE = 'ADD_SHORTCUT_FAILURE';

export const EDIT_LIST_TITLE_REQUEST = 'EDIT_LIST_TITLE_REQUEST';
export const EDIT_LIST_TITLE_SUCCESS = 'EDIT_LIST_TITLE_SUCCESS';
export const EDIT_LIST_TITLE_FAILURE = 'EDIT_LIST_TITLE_FAILURE';

export const EDIT_TODO_NAME_REQUEST = 'EDIT_TODO_NAME_REQUEST';
export const EDIT_TODO_NAME_SUCCESS = 'EDIT_TODO_NAME_SUCCESS';
export const EDIT_TODO_NAME_FAILURE = 'EDIT_TODO_NAME_FAILURE';

export const CLONE_TODOLIST_REQUEST = 'CLONE_TODOLIST_REQUEST';
export const CLONE_TODOLIST_SUCCESS = 'CLONE_TODOLIST_SUCCESS';
export const CLONE_TODOLIST_FAILURE = 'CLONE_TODOLIST_FAILURE';

export const INIT_UI_STATE_REQUEST = 'INIT_UI_STATE_REQUEST';
export const INIT_UI_STATE_SUCCESS = 'INIT_UI_STATE_SUCCESS';
export const INIT_UI_STATE_FAILURE = 'INIT_UI_STATE_FAILURE';

export const DELETE_UI_STATE = 'DELETE_UI_STATE';

export const UPDATE_CHROME_UI_STORAGE = 'UPDATE_CHROME_UI_STORAGE';

export const DELETE_SHORTCUT_REQUEST = 'DELETE_SHORTCUT_REQUEST';
export const DELETE_SHORTCUT_SUCCESS = 'DELETE_SHORTCUT_SUCCESS';
export const DELETE_SHORTCUT_FAILURE = 'DELETE_SHORTCUT_FAILURE';

export const ADD_TO_LIST_ORDER_OPTIMISTIC = 'ADD_TO_LIST_ORDER_OPTIMISTIC';
export const ADD_TO_LIST_ORDER_REAL = 'ADD_TO_LIST_ORDER_REAL';
export const DELETE_FROM_LIST_ORDER = 'DELETE_FROM_LIST_ORDER';

export const UPDATE_LIST_ORDER_SUCCESS = 'UPDATE_LIST_ORDER_SUCCESS';
export const UPDATE_LIST_ORDER_REQUEST = 'UPDATE_LIST_ORDER_REQUEST';

export const UPDATE_TODO_ORDER_SUCCESS = 'UPDATE_TODO_ORDER_SUCCESS';
export const UPDATE_TODO_ORDER_REQUEST = 'UPDATE_TODO_ORDER_REQUEST';

export const ADD_TO_TODO_ORDER_OPTIMISTIC = 'ADD_TO_TODO_ORDER_OPTIMISTIC';
export const ADD_TO_TODO_ORDER_REAL = 'ADD_TO_TODO_ORDER_REAL';
export const DELETE_FROM_TODO_ORDER = 'DELETE_FROM_TODO_ORDER';

export const SWAP_TODO_UPDATE_UI_REQUEST = 'SWAP_TODO_UPDATE_UI_REQUEST';
export const SWAP_TODO_UPDATE_UI_SUCCESS = 'SWAP_TODO_UPDATE_UI_SUCCESS';

export const CHANGE_LIST_COLOR = 'CHANGE_LIST_COLOR';

export const SET_API_KEY = 'SET_API_KEY';
