export const TOGGLE_TODO_REQUEST = 'TOGGLE_TODO_REQUEST';
export const TOGGLE_TODO_SUCCESS = 'TOGGLE_TODO_SUCCESS';
export const TOGGLE_TODO_FAILURE = 'TOGGLE_TODO_FAILURE';

export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE';

export const ADD_TODOLIST_REQUEST = 'ADD_TODOLIST_REQUEST';
export const ADD_TODOLIST_OPTIMISTIC_SUCCESS = 'ADD_TODOLIST_OPTIMISTIC_SUCCESS';
export const ADD_TODOLIST_REAL_SUCCESS = 'ADD_TODOLIST_REAL_SUCCESS';
export const ADD_TODOLIST_FAILURE = 'ADD_TODOLIST_FAILURE';

export const INIT_APP_REQUEST = 'INIT_APP_REQUEST';
export const INIT_APP_SUCCESS = 'INIT_APP_SUCCESS';
export const INIT_APP_FAILURE = 'INIT_APP_FAILURE';

export const INIT_TODOLISTS_REQUEST = 'INIT_TODOLISTS_REQUEST';
export const INIT_TODOLISTS_SUCCESS = 'INIT_TODOLISTS_SUCCESS';
export const INIT_TODOLISTS_FAILURE = 'INIT_TODOLISTS_FAILURE';

export const INIT_A_TODOLIST = 'INIT_A_TODOLIST';

export const DELETE_TODOLIST_REQUEST = 'DELETE_TODOLIST_REQUEST';
export const DELETE_TODOLIST_SUCCESS = 'DELETE_TODOLIST_SUCCESS';
export const DELETE_TODOLIST_FAILURE = 'DELETE_TODOLIST_FAILURE';

export const CHANGE_FILTER = 'CHANGE_FILTER';

export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE';

export const SWAP_TODO_REQUEST = 'SWAP_TODO_REQUEST';
export const SWAP_TODO_SUCCESS = 'SWAP_TODO_SUCCESS';
export const SWAP_TODO_FAILURE = 'SWAP_TODO_FAILURE';
